import { describe, expect, it } from "vitest";
import ExcelJS from "exceljs";
import { buildDailyReportTemplate } from "@/lib/xlsx-template";
import { parseDailyReportXlsx } from "@/lib/xlsx-parse";

const baseInput = {
  transportadoraId: "transp-1",
  transportadoraNome: "Transportadora Teste",
  dataReport: new Date(2026, 6, 24),
  dataResultadoDiaAnterior: new Date(2026, 6, 23),
  dataPreviaDiaAtual: new Date(2026, 6, 24),
  responsavelNome: "Fulano de Tal",
  responsavelEmail: "fulano@example.com",
  observacoes: "Observação de teste",
  previousDayMetrics: {
    totalPedidos: 33,
    totalNoPrazo: 15,
    totalForaDoPrazo: 18,
    totalEntregue: 14,
    totalEmAberto: 19,
    totalTentativaInsucesso: 0,
    totalDevolucao: 0,
    totalCancelado: 0,
  },
  currentDayPreviewMetrics: {
    totalPedidos: 44,
    totalFinalizado: 12,
    totalEmAberto: 32,
    totalEntregue: 12,
    totalTentativaInsucesso: 0,
    totalDevolucao: 0,
    totalCancelado: 0,
    finalizadosNoPrazo: 12,
    finalizadosForaDoPrazo: 0,
  },
  ufMetrics: [
    { uf: "BA", dentroDoPrazo: 12, foraDoPrazo: 0 },
    { uf: "PB", dentroDoPrazo: 15, foraDoPrazo: 0 },
    { uf: "RJ", dentroDoPrazo: 4, foraDoPrazo: 0 },
    { uf: "RR", dentroDoPrazo: 2, foraDoPrazo: 0 },
  ],
};

describe("parseDailyReportXlsx", () => {
  it("round-trips a template generated by buildDailyReportTemplate", async () => {
    const buffer = await buildDailyReportTemplate(baseInput);
    const result = await parseDailyReportXlsx(buffer, "transp-1");

    expect(result.ok).toBe(true);
    if (!result.ok) return;

    expect(result.values.dataReport).toBe("2026-07-24");
    expect(result.values.dataResultadoDiaAnterior).toBe("2026-07-23");
    expect(result.values.submittedByName).toBe("Fulano de Tal");
    expect(result.values.submittedByEmail).toBe("fulano@example.com");
    expect(result.values.observacoes).toBe("Observação de teste");

    expect(result.values.prev_totalPedidos).toBe("33");
    expect(result.values.prev_totalNoPrazo).toBe("15");
    expect(result.values.prev_totalForaDoPrazo).toBe("18");

    expect(result.values.cur_totalPedidos).toBe("44");
    expect(result.values.cur_totalFinalizado).toBe("12");

    expect(result.values.uf_BA_dentro).toBe("12");
    expect(result.values.uf_RR_dentro).toBe("2");
    expect(result.values.uf_SP_dentro).toBe("0");
  });

  it("rejects a file generated for a different transportadora", async () => {
    const buffer = await buildDailyReportTemplate(baseInput);
    const result = await parseDailyReportXlsx(buffer, "transp-outra");

    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.errors.some((message) => message.includes("outra transportadora"))).toBe(true);
  });

  it("rejects a file with a missing sheet", async () => {
    const buffer = await buildDailyReportTemplate(baseInput);
    const workbook = new ExcelJS.Workbook();
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    await workbook.xlsx.load(buffer as any);
    workbook.removeWorksheet(workbook.getWorksheet("UF - Dia anterior")!.id);
    const mutatedBuffer = Buffer.from(await workbook.xlsx.writeBuffer());

    const result = await parseDailyReportXlsx(mutatedBuffer, "transp-1");
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.errors.some((message) => message.includes("UF - Dia anterior"))).toBe(true);
  });

  it("rejects a non-numeric value in a numeric field", async () => {
    const buffer = await buildDailyReportTemplate(baseInput);
    const workbook = new ExcelJS.Workbook();
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    await workbook.xlsx.load(buffer as any);
    const sheet = workbook.getWorksheet("Dia anterior")!;
    sheet.getRow(2).getCell(1).value = "não é número";
    const mutatedBuffer = Buffer.from(await workbook.xlsx.writeBuffer());

    const result = await parseDailyReportXlsx(mutatedBuffer, "transp-1");
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.errors.some((message) => message.includes("Total de pedidos"))).toBe(true);
  });
});
